// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently,
// but are changed infrequently

#pragma once


#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

#define _WIN32_WINNT 0x0601
#define WINVER 0x0601

//#define _USE_32BIT_TIME_T
#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS	// some CString constructors will be explicit

#include <afx.h>
#include <afxwin.h>
#include <afxdisp.h>

#include <map>
#include <bitset>
#include <vector>
#include <sstream>
#include <string>
#include <xstring>
#include <list>
#include <array>


using namespace std;
using namespace std::rel_ops; // !=, >, <=, >=; generated by default

//#include "utAssert.h"
//#include "utDateTime.h"
//#include "utDateTimeSpan.h"

#include "LDAPLogger.h"
